---
# Playbook to deploy Ghost and its components
# TO DO
- name: Deploy Redis
  hosts: localhost
  gather_facts: false
  roles:
    - redis
  tags:
    - redis_install
    
- name: Deploy Database
  hosts: localhost
  gather_facts: false
  roles:
    - ghost_db
  tags:
    - db_install

- name: Deploy Ghost
  hosts: localhost
  roles:
    - ghost
  tags:
    - ghost_install

