#Undeploy Ghost
- name: Get ghost deployment
  kubernetes.core.k8s_info:
    kind: Deployment
    label_selectors:
      - app=ghost
  register: ghost_deployment

- name: Undeploy Ghost deployment
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ ghost_deployment.resources[0] }}"
  when: ghost_deployment.resources | length > 0

- name: Wait for Ghost deployment to be deleted
  kubernetes.core.k8s_info:
    kind: Deployment
    label_selectors:
      - app=ghost
  register: ghost_deployment
  until: ghost_deployment.resources | length == 0
  retries: 10
  delay: 10

- name: Get ghost service
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app=ghost
  register: ghost_service

- name: Undeploy Ghost service
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ ghost_service.resources[0] }}"
  when: ghost_service.resources | length > 0

- name: Wait for ghost service to be deleted
  kubernetes.core.k8s_info:
    kind: Service
    label_selectors:
      - app=ghost
  register: ghost_service
  until: ghost_service.resources | length == 0
  retries: 10
  delay: 10

- name: Get Autoscaling
  kubernetes.core.k8s_info:
    kind: HorizontalPodAutoscaler
    label_selectors:
      - app=ghost
  register: ghost_hpa

- name: Undeploy autoscaling
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ ghost_hpa.resources[0] }}"
  when: ghost_hpa.resources | length > 0

- name: Wait for autoscaling to be deleted
  kubernetes.core.k8s_info:
    kind: HorizontalPodAutoscaler
    label_selectors:
      - app=ghost
  register: ghost_hpa
  until: ghost_hpa.resources | length == 0
  retries: 10
  delay: 10
