---
- name: Get Mysql Persistent Volume Claim
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_pvc

- name: Undeploy Mysql Persistent Volume Claim
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_pvc.resources[0] }}"
  when: mysql_pvc.resources | length > 0

- name: Get Mysql Persistent Volume
  kubernetes.core.k8s_info:
    kind: PersistentVolume
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_pv

- name: Undeploy Mysql Persistent Volume
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_pv.resources[0] }}"
  when: mysql_pv.resources | length > 0

- name: Get Mysql Storage Class
  kubernetes.core.k8s_info:
    kind: StorageClass
    label_selectors:
      - app=mysql
      - tier=database
  register: mysql_storage_class

- name: Undeploy Mysql Storage Class
  kubernetes.core.k8s:
    state: absent
    namespace: default
    definition: "{{ mysql_storage_class.resources[0] }}"
  when: mysql_storage_class.resources | length > 0